apiVersion: v1
kind: Secret
metadata:
  name: {{ template "loki.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "loki.name" . }}
    chart: {{ template "loki.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if .Values.configString }}
  loki.yaml: {{ tpl .Values.configString . | b64enc}}
{{- else }}
  loki.yaml: {{ tpl (toYaml .Values.config) . | b64enc}}
{{- end }}
